apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: domain-fullnode
  namespace: demo
spec:
  secretName: domain-fullnode-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  duration: 2160h # 90d
  renewBefore: 720h # 30d before SSL will expire, renew it
  dnsNames:
    - "haidv.tech"
    - "*.haidv.tech"
