apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
 name: eks-demo
 region: ap-southeast-1
 version: '1.24'
managedNodeGroups:
 - name: nodegroup
   instanceType: t3.medium
   minSize: 2
   maxSize: 3
